apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgenode-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # this is a local path volume
  hostPath:
    path: "/mnt/data/edgenode"
---
#pvc for models
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgenode-pvc
  namespace: naeural
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: edgenode-pv